ReddyLab/CRADLE

.pylintrc, CRADLE/CorrectBias/vari.py
Adds .pylintrc that sets coding standards for the project.
Additionally, fixes some of the linting issues in one file just as an example.
=> Add python linter

.gitignore, MANIFEST.in, Makefile, README.md, pyproject.toml, setup.cfg, setup.py
Brings building and installing process for cradle in line with PEPs [517](https://www.python.org/dev/peps/pep-0517/) and [518](https://www.python.org/dev/peps/pep-0518/).
Adds a makefile so the process is easy.
=> Updates build/install methods

CRADLE/CallPeak/calculateRC.pyx
This changes snake_case to camelCase, splits a long line into several shorter lines,
adds some spacing around operators, and deletes some commented out code.
=> More linting for CallPeak/calculateRC.pyx

CRADLE/CorrectBias/calculateOnebp.pyx
Primarily:
snake_case to camelCase
superfluous parenthesis in control flow structures (while/if)
unnecessary comparisons to True/False (some _are_ necessary, primarily as an argument to 'np.where')
changes == None to is None and != None to is not None where applicable
(which is not everywhere! the ==/!= is correct as an argument to 'np.where')
=> Fixes a some linter issues with CorrectBias/calculateOnebp.pyx

CRADLE/CorrectBiasStored/calculateOneBP.pyx, CRADLE/CorrectBiasStored/vari.py
Also changes the COVARI_Name global to be all caps - COVARI_NAME
=> Changes snake_case to camelCase in correctBiasStored/vari.py

.gitignore, CRADLE/CorrectBiasStored/__init__.py, CRADLE/CorrectBiasStored/calculateOneBP.pyx, CRADLE/CorrectBiasStored/correctBias.py, CRADLE/CorrectBiasStored/vari.py, bin/cradle
I think the code generally will be improved by passing function arguments
around explicitly, instead of implicitly using global variables.. Initially this may
mean having a lot of arguments to some functions but as we continue to refactor we'll
hopefully be able to improve the situation.
The reason I think this will be helpful is because it makes "control flow" explicit
and easier to follow. It becomes clear what must be called in what order. It also
makes it easier to see what data each function needs, which make the functions
easier to understand and reason about.
=> Removes global variable references from calculatedOneBP.pyx

CRADLE/CorrectBiasStored/calculateOneBP.pyx, CRADLE/CorrectBiasStored/correctBias.py, CRADLE/CorrectBiasStored/vari.py
It was swapped for FRAGLEN instead of FILTERVALUE.
Also changes MIN_FRAG_FILTER_VALUE to MIN_FRAGNUM_FILTER_VALUE, which is
preferred by Young-Sook.
=> MIN_FRAG_FILTER_VALUE was swapped for the wrong constant

CRADLE/CorrectBiasStored/calculateOneBP.pyx
I think this factoring makes the code easier to follow and understand. It's broken down into more
functions which allows for code reuse and the computing code is more clearly deliniated from the
graph plitting code.
In my testing the output is exactly the same as the code without these changes.
=> Refactors performRegression in CorrectBias_stored

CRADLE/CorrectBiasStored/calculateOneBP.pyx
This reduces the number of temp files created, as only temp files that
are actually used will be created. Additionally, these files will only
be opened once instead of twice.
Some code is mostly just rearranged to group related code.
=> Refactors correctReadCount and related functions some

.gitignore, CRADLE/CorrectBiasStored/calculateOneBP.pyx, CRADLE/CorrectBiasStored/correctBias.py, CRADLE/CorrectBiasStored/vari.py, CRADLE/correctbiasutils/__init__.py, CRADLE/correctbiasutils/cython.pyx, setup.cfg, setup.py
This is in preparation for also factoring it out of correctBias/correctBias.py,
eliminating a lot of code duplication between the two modules.
Tested using test data and this outputs the same results as without these changes.
=> Factors a lot of code out of correctBiasStored/correctBias.py

CRADLE/CorrectBiasStored/calculateOneBP.pyx
Instead of using for loops to manually copy data, one by one, uses numpy's
built-in features to copy and shape data.
This seems to speed up loading the data by 500-700x.
=> Changes how hdf5 files are loaded in CorrectBias_stored

CRADLE/CorrectBias/calculateOnebp.pyx, CRADLE/CorrectBias/correctBias.py, CRADLE/CorrectBias/vari.py, README.md, bin/cradle
Adds the ability, like CorrecrtBias_stored has, to seed the random number generator. This
allows runs to be reproducable.﻿
=> Add ability to seed RNG to correctBias

CRADLE/CorrectBias/calculateOnebp.pyx, CRADLE/CorrectBiasStored/calculateOneBP.pyx, CRADLE/correctbiasutils/cython.pyx
Both packages plot the same way, so this code can be shared between the two.
=> Factors "plot" out of CorrectBias and CorrectBias_stored

CRADLE/CorrectBias/calculateOnebp.pyx
converts "x = x + y" to "x += y"
uses context managers ("with")
makes global variables arguments
uses enumerate and iterables instead of ranges
changes some names to match CorrectBias_stored's "selectIdx"
=> Make CorrectBias selectIdx more "pythonic"

CRADLE/CorrectBias/correctBias.py, CRADLE/correctbiasutils/__init__.py, CRADLE/correctbiasutils/cython.pyx
Running this function on my test dataset initially took about 25 minutes.
I changed the algorithm itself and used some more of the features of
numpy and pyBigWig. These changes brought the time down to ~15 minutes.
Then I moved the function into cython and made a lot of the scalar variables cdefs
and created a MemoryView for the two numpy arrays. These changes brought the time
down to ~2.5 minutes!
I don't have tests, but I compared the output, using diff, to a known good output
from an earlier run on the same data and there is no difference in the files.
=> Improves speed of generateNormalizedObBWs ~10x

CRADLE/CorrectBiasStored/calculateOneBP.pyx, CRADLE/CorrectBiasStored/correctBias.py, CRADLE/correctbiasutils/__init__.py, CRADLE/correctbiasutils/cython.pyx
The new output format is a binary format that better matches the needs
of the eventual merge into a bigwig file.
Fewer correctReadCount jobs means orders of magnitude fewer temp files are made. A little
more memory is used because the temp file writes are "buffered". But combining the files
takes ~10x less time -- from ~120 sec to ~12 sec in my testing.
In that same testing I checked how large the buffers get, and they don't get very large:
correct read count data size: 12.144279 MB
correct read count data size: 13.848162 MB
correct read count data size: 15.755831 MB
correct read count data size: 18.430004 MB
correct read count data size: 24.168723 MB
correct read count data size: 23.287973 MB
correct read count data size: 28.332615 MB
correct read count data size: 28.84925 MB
correct …
=> [PERF] Changes temp file format, creates fewer correctReadCount jobs

CRADLE/correctbiasutils/cython.pyx, tests/test_correctbiasutils.py
Cython requires some special changes to get importing to work.
=> Changes to get pytest to run in github actions

README.md, cradle_singularity.def
Adds a blurb about the definition file and running the image to the README.
Removes a lot of extraneous spaces at the end of lines from the README
=> Adds Singularity image definition file

CRADLE/CorrectBiasStored/calculateOneBP.pyx, tests/CorrectBiasStored/getcoefs_test.py
Also simplifies getCoefs a little.
=> Adds tests for getCoefs function

CRADLE/correctbiasutils/__init__.py, tests/correctbiasutils/init_test.py, tests/correctbiasutils/rotatebwfilearrays_test.py
More tests are coming, these were some low-hanging fruit.
=> Creates some tests for function in correctbiasutils

CRADLE/correctbiasutils/__init__.py, tests/correctbiasutils/init_test.py, tests/mocks/BigWig.py, tests/mocks/BigWig_test.py
This required a little bit of refactoring the function and creating a mock
"BigWig" object that can be inspected and added to without worrying about
the filesystem. I think the mock BigWig object will be useful for other tests
as well.
=> Adds a test for generateNormalizedObBWs

tests/correctbiasutils/init_test.py
The mean calculation results are floats, which are not exact, so they are compared using a
numpy function specifically for comparing floats, "allclose". A reasonably small margin of
difference, 0.00001, is passed in.
=> Adds tests for utils.regionMeans

CRADLE/CorrectBiasStored/calculateOneBP.pyx, CRADLE/CorrectBiasStored/correctBias.py, CRADLE/CorrectBiasStored/vari.py, CRADLE/correctbiasutils/__init__.py, README.md, bin/cradle, tests/correctbiasutils/init_test.py, tests/mocks/BigWig.py, tests/mocks/TwoBit.py, tests/mocks/TwoBit_test.py
FKA alignCoordinatesToHDF
The test itself isn't much, beyond the creation of a new class mocking
a py2bit object.
However, it took a while to understand what all the pieces of the function were
and what all the magic numbers did. This led to changes throughout CorrectBiasStored
that, I think, improve the clarity of the code.
Also, I fixed some typos in the README and bin/cradle files and added information about deprecating "-faFile".
=> Adds test for alignCoordinatesToCovariateFileBoundaries

.gitignore, CRADLE/CorrectBias/calculateOnebp.pyx, CRADLE/CorrectBias/correctBias.py, CRADLE/CorrectBias/vari.py, CRADLE/CorrectBiasStored/calculateOneBP.pyx, CRADLE/CorrectBiasStored/correctBias.py, CRADLE/CorrectBiasStored/vari.py, CRADLE/correctbiasutils/__init__.py, tests/correctbiasutils/dividegenome_test.py, tests/correctbiasutils/init_test.py
FKA TrainingRegion and TrainingRegionSet -- now that these classes aren't just used
for training data, the names didn't make much sense.
These classes are useful and were always intended to replace the tuples/lists that
were used throughout the codebase. These changes complete that goal.
Because the use of the tuples was so pervasive a lot of seemingly unrelated changes,
especially in CorrectBias which had not had much refactoring done, had to be made.
These generally replace code that had, at one point, been duplicated between
CorrectBias and CorrectBiasStored.
=> Use the "ChromoRegion" and "ChromoRegionSet" classes more

CRADLE/correctbiasutils/__init__.py
After having some memory trouble with the new OO api, this changes
back to the older pyplot api.
=> Revert matplotlib api used

CRADLE/CorrectBiasStored/correctBias.py
* Makes output consistent
* Makes output more compact
* Changes timing output to be of just a section rather than a running total
* the final output shows the total run time
* Most timings are in minutes instead of hours -- I think that's often
a more useful scale
* Creates some more sections
Example:
```
======  INITIALIZING PARAMETERS ....
RNG Seed: 1437572394
======  COMPLETED INITIALIZING PARAMETERS ....
======  SELECTING TRAINING SETS ....
-- Getting candidate training sets ....
-- Completed getting candidate training sets .... : 0.003719214598337809 min
-- Filling Training Sets ....
-- Completed filling training sets .... : 0.012057816982269287 min
-- Selecting training sets from trainSetMeta ....
-- Completed selecting training sets from trainSetMeta : 0.00015371243158976238 min(s) …
```
=> Modifies the correctBiasStored logging output

CRADLE/CorrectBiasStored/regression.py, setup.py
This function is pretty fast and having it compiled to cython doesn't
seem to help all that much.
Converting it back to python will make future maintenance easier.
=> Converts regression.pyx to regression.py

CRADLE/CalculateCovariates/taskCovariates.pyx
These are mostly of the "use numpy efficiently" variety.
=> More optimizations for covariate calculations

CHANGELOG.md, cradle_singularity.def, setup.cfg
=> Bumps the CRADLE version to 0.27.0

CRADLE/Normalize/normalize.py
1) mergeRegions create 0-length overlaps. if two regions are next to
each other the get merged, but they don't overlap. A zero-length
overlap is created, which can cause a problem later when trying to
get reads from the bigwig file.
2) region_overlap entries might have the wrong end.
(line 80) region_overlapped.append([currChromo, currStart, pastEnd])
is incorrect if currEnd is < pastEnd. Changed to
region_overlapped.append([currChromo, currStart, min(currEnd, pastEnd)])
3) excludeOverlapRegion didn't fully separate region overlap cases.
"overlap regions end inside the target region" and "overlap regions
start inside the target region" can share some overlaps when one
starts _and_ ends in the same region. This Fourth case is now
handled separately.
4) in excludeOverlapRegion calculating …
=> Fixes a few problems with region calculations in the normalize command
