- CRADLE/CallPeak/calculateRC.pyx
- CRADLE/CorrectBias/correctBias.py
- CRADLE/CorrectBiasStored/correctBias.py
- CRADLE/CorrectBiasStored/vari.py
All these reverts have to do with numpy arrays. Treating a numpy array of booleans is incorrect. For instance,
'array == False' is not the same as 'not array'. The first inverts all the booleans in the array. The second
evaluates to False, assuming 'array' is a truthy value.
> Reverts some equality check changes suggested by linter

- .pylintrc
- CRADLE/CorrectBiasStored/calculateOneBP.pyx
- CRADLE/CorrectBiasStored/correctBias.py
- CRADLE/CorrectBiasStored/vari.py
- README.md
- bin/cradle
- setup.cfg
This option will eventually be added to CorrectBias as well.
To get repeatable runs I had to factor out the part of performRegression that called
np.random.choice because it's called from two different processes and the order would
be non-deterministic.
Additionally, I changed some variable names to be more descriptive, added a "label"
argument to performRegression so the output files of the process that finishes first
won't be clobbered by the output files of the process that finishes second.
Finally, I created some Cython classes to use instead of lists of 3-tuples for Training
Sets and Training Regions.
> Adds -rngSeed option to CorrectBias_stored

- CRADLE/CorrectBias/correctBias.py
- CRADLE/CorrectBiasStored/correctBias.py
- CRADLE/correctbiasutils/__init__.py
It also adds some comments to divideGenome and simplifies the code, which is hopefully clearer.
I did some ad hoc testing with the following script to make sure the new and old results were the same:
```python
def divideGenome1(regions, baseBinSize=1, genomeBinSize=50000):
genomeBinSize -= genomeBinSize % baseBinSize
tasks = []
for region in regions:
regionStart = int(region[0])
regionEnd = int(region[1])
binStart = regionStart
while binStart < regionEnd:
binEnd = binStart + genomeBinSize
tasks.append((binStart, min(binEnd, regionEnd)))
binStart = binEnd
return tasks
def divideGenome2(regions, baseBinSize=1, genomeBinSize=50000):
genomeBinSize = int(genomeBinSize / float(baseBinSize)) * baseBinSize
tasks = []
for region in regions:
regionStart = int(region[0])
regionEnd = int(region[1]) …
```
> Factors divideGenome out of CorrectBias

- CRADLE/correctbiasutils/__init__.py
When there is only a single bin the results of pyBigWig.stats was
being treated like a scalar value even though it was actually an
array with one value in it.
The fix here is just to get that value out of the array.
> Fixes single bin fillTrainingSetMeta bug

- CRADLE/correctbiasutils/__init__.py
- CRADLE/correctbiasutils/cython.pyx
- setup.cfg
Using the pyBigWig stats method to calculate means is pretty slow. Additionally,
the "binning" algorithm is opaque and inscrutable.
This creates new methods for calculating the means and doing the binning which are currently
used for training set calculations. This makes mean calculation significantly faster than
using pyBigWig with more control over the binning algorithm.
Hopefully this machinery can also be used to replace binning and mean calculations in
calculating task covariates, which would provide significant speedup and simplify the
code quite a bit.
**Note,** however, that this breaks "backwards compatibility" with versions prior to this one (0.23). This means the same data input will result in a slightly different output.
Additionally, I	made writes to the training set file (in …
> Improves mean calculation

- CRADLE/correctbiasutils/cython.pyx
Added a check to writeBedFile and coalesceSections when setting the
end of the last region to analysisEnd. The purpose of that check was
to not include data that we didn't want to analyize. But the check also
needed to account for the situation where analysisEnd was bigger than
than the end of the last region. That's what changing `x = analysEnd`
to `x = min(x, analysisEnd)` does.
I also noticed that coalesceSections, which I adapted from
generateNormalizedObBWs, still uses '1' instead of 'binSize' in a couple
of places. This corrects the oversight.
> [BUGFIX] Sections not filtered, coalescing wrong

- CRADLE/CorrectBiasStored/calculateOneBP.pyx
- CRADLE/correctbiasutils/__init__.py
- tests/test_correctbiasutils.py
This creates n copies of one list, not n lists. This means that
In [1]: a = [[]] * 5
In [2]: a[0].append(1)
In [3]: a
Out[3]: [[1], [1], [1], [1], [1]]
Which is not what we want.
In [1]: a = [[] for _ in range(5)]
In [2]: a[0].append(1)
In [3]: a
Out[3]: [[1], [], [], [], []]
is the desired behavior.
Pulls out the "rotate matrix of strings" code so it can be tested.
> [BUGFIX] Creating multiple lists like [[]] * n is incorrect

- CRADLE/CorrectBias/calculateOnebp.pyx
- CRADLE/CorrectBias/correctBias.py
- CRADLE/CorrectBiasStored/calculateOneBP.pyx
- CRADLE/CorrectBiasStored/correctBias.py
- CRADLE/correctbiasutils/__init__.py
- CRADLE/correctbiasutils/cython.pyx
Previously the the high percentile read counts for a bw file were plotted
separately from the rest of the read counts. This combines the two into a
single plot.
To avoid using too much memory the read counts are returned from performRegression
pre-sampled.
> Combines read count plots

- CRADLE/correctbiasutils/__init__.py
- CRADLE/correctbiasutils/cython.pyx
- tests/correctbiasutils/coalescesections_test.py
There were some small issues with coalesceSections that are fixed.
Replaces the code in generateNormalizedObBWs that duplicates the
functionality of coalesceSections with a call to coalesceSections.
Move generateNormalizedObBWs out of cython.pyx, since it no longer
contains code that will get a speed boost from cython.
> Creates tests for coalesceSections

- CRADLE/CorrectBiasStored/calculateOneBP.pyx
- tests/CorrectBiasStored/getreadcounts_test.py
Refactoring was necessary to make this testable without a dummy
bigwig file. Now the "read from a file" part is completely separate
and any iterable can be passed in to getReadCounts
> Refactors getReadCounts and adds tests

- CRADLE/CorrectBias/calculateOnebp.pyx
- CRADLE/CorrectBias/vari.py
- CRADLE/CorrectBiasStored/calculateOneBP.pyx
- CRADLE/CorrectBiasStored/correctBias.py
- CRADLE/CorrectBiasStored/vari.py
- CRADLE/correctbiasutils/__init__.py
- README.md
- bin/cradle
"fa" was short for "fasta", a file format. However, the data format CRADLE
expects is 2bit, so the name was misleading on that account.
Beyond the inaccuracy of the names, though, I don't think they described the
right thing. The file contains the sequences of the human genome and that's
what's important -- not the file format. So I've changed all the references
from fa/FA/etc. to genome/GENOME/etc.
The old "-faFile" command line argument still works, for backwards compatability,
but it's no longer documented and should be considered deprecated.
> Renames FA/faFile/fa to genome

- .github/workflows/python-app.yml
- CRADLE/CorrectBias/vari.py
- CRADLE/CorrectBiasStored/vari.py
- CRADLE/correctbiasutils/__init__.py
- Makefile
- tests/CorrectBias/vari_test.py
- tests/CorrectBiasStored/vari_test.py
- tests/correctbiasutils/chromoregion_test.py
- tests/correctbiasutils/chromoregionset_test.py
- tests/mocks/BigWig.py
- tests/mocks/BigWig_test.py
Some code, like the region loading code in vari.py, can be simplified and
clarified by breaking it up into parts (merge regions, subtract regions, etc.)
and moving those into ChromoRegion* methods.
This made the ChromoRegion* classes bigger and a bit more complex, so I've added
reasonably comprehensive tests for them.
I also decided to add type annotations to demonstrate that. You can check the types by running
mypy CRADLE/correctbiasutils
(after installing mypy with `pip install mypy`)
Finally, I did some refactoring of CRADLE.CorrectBias*.vari.setAnlaysisRegion so setAnalysisRegion
can be tested, and added tests.
> More fully flesh out ChromoRegion* classes

- CRADLE/CorrectBias/correctBias.py
- CRADLE/CorrectBiasStored/calculateOneBP.pyx
- CRADLE/correctbiasutils/__init__.py
- CRADLE/correctbiasutils/cython.pyx
- tests/correctbiasutils/chromoregionset_test.py
- tests/correctbiasutils/coalescesections_test.py
- tests/correctbiasutils/init_test.py
This bigwig issue was that the order of the chromosomes in the header created
for the new bigwig files did not match the order that data was added to the
bigwig files. The chromosome data used to create the header was an unordered set,
so the order was more-or-less random.
The fix is to use a list instead of a set. The list gets updated when the set is added to or sorted.
That's not exactly true -- the list update is deferred until it's the list is needed.
A change was made correctReadCounts a while ago that stored the new read
count data until it could be done in a single write. As data sets get bigger
and more regions are covered this became untenable -- memory usage shot way,
way up.
These change moves back to "write data immediately" model. Instead of writing
a bed file, though, a …
> Fixes Memory and BW Region Order Problems

- CRADLE/CorrectBiasStored/vari.py
- CRADLE/correctbiasutils/__init__.py
According to https://pythonspeed.com/articles/python-object-memory/ and
https://docs.python.org/3.9/reference/datamodel.html#object.__slots__
Setting __slots__ will both decrease memory usage and potentially speed up
member access. In my testing a ChromoRegion only take about half the space it
did without __slots__. As there can be a lot of ChromoRegion, this is tens, if
not hundreds of megabytes of memory savings.
There are probably similar savings per object for ChromoRegionSet and StoredCovariates
but there aren't many of those objects, so it's not as big a win.
> Adds explicit "slots" to classes

- CRADLE/CorrectBiasStored/readCounts.pyx
This way the covariate read and selection is only done once. This gave a slight, but noticable, speedup in my testing.
> Factors covariate reads out calculations

- CRADLE/CorrectBias/correctBias.py
- CRADLE/CorrectBiasStored/correctBias.py
These functions are decorated with `@timer`, like CorrectBiasStored/correctBias.py
This gives some nice structure to the document and makes the timing output more standard.
Sample output:
```
********************************************************************************
* The "-faFile" argument has been deprecated in favor of "-genome" and may be  *
* removed in a future release. The functionality isn't changing, just the      *
* argument name. Please update your scripts to use "-genome".                  *
********************************************************************************
======  INITIALIZING PARAMETERS ....
RNG Seed: 1147029956
======  COMPLETED INITIALIZING PARAMETERS .... : 8.949900000000029e-05 min(s)
======  SELECTING TRAINING SETS ....
--  Getting Candidate …
```
> Factors "run" function in CorrectBias/correctBias.py into multiple functions

- CRADLE/CorrectBias/vari.py
- CRADLE/CorrectBiasStored/vari.py
- CRADLE/correctbiasutils/vari.py
-mi, -norm, -generateNormBW, and -rngSeed are not common to _all_
sub-programs. I removed them from correctbiasutils/vari.py and added
them to the vari.pys that do use them.
I also changed how -bl is checked because it is also not common to
all sub-programs.
> Removes some "common" arguments from correctbiasutils/vari.py

- CRADLE/CallPeak/calculateRC.pyx
- CRADLE/CallPeak/callPeak.py
- CRADLE/CallPeak/vari.py
Factoring out common vari methods and changing callPeak to use the
ChromoRegion/ChromoRegionSet classes is more work than its worth
right now (someone needs to use it today).
Reverting callPeak.py and callPeak/vari.py to be independent of the
rest of CRADLE.
> Reverts using a common vari.py with callPeak

- CRADLE/CorrectBiasStored/readCounts.pyx
- CRADLE/correctbiasutils/__init__.py
- CRADLE/correctbiasutils/cython.pyx
- tests/correctbiasutils/init_test.py
coalesceSections coerces all values to integers, which truncates them.
This can result in some inaccuracies in the resulting data (e.g.,
3.0 instead 4.0 for a value of 3.7).
This change rounds values to the nearest integer before passing the
data to coalesceSections which will give more accurate output.
> Rounds CorrectBiasStored results before coalescing sections

- CRADLE/CorrectBias/vari.py
- README.md
- bin/cradle
Instead of having the user input the gquadmax value, the value is
calculated from the gquad files themselves. Each file has a header
that contains the maxVal in the file, rounded down to the nearest
integer. The largets maxVal across all the gquad files will be used
as the GQUAD_MAX value.
> Removes gquadmax argument from correctBias command

- CRADLE/CallPeak/callPeak.py
- CRADLE/CallPeak/vari.py
CRADLE calculates an effect size by s1ubtraction and this sometimes makes it hard to compare the cradle effect size with the effect size of other data sets. To get around this problem, 'pseudo log2fc' is calculated and added to the peak output file. 
Pseudo log2fc is calculated by adding the same constant to both `inputCount` and `outputCount` to make the resulting two values positive and then calculating log2fc. 
The constant is determined by taking the max(`normalizedInputCount`-`inputCount`, `normalizedOutputCount`-`outputCount`). Here, `normalizedInputCount` and `normalizedOutputCount` are calculated by using normalized observed control bigwigs and experimental bigwigs—those bigwigs are from new optional arguments called `-normCtrlbw` and `-normExpbw`, respectively.
> adding pseudo log2fc in peak output file

- CRADLE/CallPeak/callPeak.py
Returns np.nan instead. Also shows warning when this happens.
Also fixes some code-style problems
> Fixes Cohen's D divide-by-zero error 

- CHANGELOG.md
- CRADLE/CorrectBias/vari.py
- CRADLE/CorrectBiasStored/vari.py
- README.md
This is the "minimum fragment count" argument. Locations with fewer
fragments will be ignored.
> Changes default value for -mi argument

- .gitignore
- CHANGELOG.md
- CRADLE/CallPeak/calculateRC.py
- CRADLE/CallPeak/calculateRC.pyx
- CRADLE/CallPeak/callPeak.py
- CRADLE/CallPeak/vari.py
- setup.cfg
- setup.py
Speeds up call peaks a little, but brings the code much closer to idiomatic python.
* Makes calculateRC.pyx a regular python file. Nothing was gained from it being cython.
* Uses one multiprocessing pool instead of lots
* Combines variance and region cutoff calculations into one step -- the data from was one fed directly into the other anyway, this saves some multiprocessing round trip time.
* Simplifies REGION list as a numpy array.
* minimizes how often bigwigs are read
> Callpeak speedup
